### PR TITLE
FIX: Update namespaces again

### PR DESCRIPTION
**Pull request by effigies**
Starting by ensuring that `pydra.engine` can also be imported.

### CODE REVIEW

**Comment by effigies** [comment]
Huh. I was unable to reproduce the failure I was having with `pydra-nipype1`. I will come back to this again...

**Comment by effigies** [comment]
Did manage to reproduce the issue by trying to directly import `pydra` after installing the task package.

**Comment by satra** [comment]
> manage to reproduce the issue

but also seems like you fixed the issue?

**Comment by effigies** [comment]
Yes, reproduced and fixed, again using nipype/pydra#309.

**Comment by satra** [comment]
@effigies - this looks good to me. in terms of this being copied or imported into a repo, should we ask people to keep these tests in place and adjust the tests as necessary in the readme.

**Comment by effigies** [comment]
Started to update the README, but went beyond discussing tests. I'll merge this and open a new PR.

**Pull request merged**
